name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      npm_tag:
        description: npm dist-tag to publish with
        type: choice
        default: auto
        options:
          - auto
          - alpha
          - latest

concurrency: release-${{ github.ref }}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm
          registry-url: https://registry.npmjs.org

      - name: Setup npm trusted publishing support
        run: npm install -g npm@^11.5.1

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Release
        uses: changesets/action@v1
        with:
          version: pnpm release:version
          publish: pnpm release:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NPM_TAG: ${{ github.event.inputs.npm_tag || 'auto' }}
